# Use a slim Python image
FROM --platform=linux/amd64 python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy your app code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_call_analysis.txt



# Set default command
CMD ["python", "app/service/call_analysis/call_analysis.py"]