"""initial schema with enums

Revision ID: 00d4e5c405dc
Revises: 
Create Date: 2025-04-19 18:50:11.932265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d4e5c405dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_number', sa.String(length=15), nullable=False),
    sa.Column('seller_number', sa.String(length=15), nullable=False),
    sa.Column('call_type', sa.Enum('INCOMING', 'OUTGOING', name='calldirection'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exotel_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_from', sa.String(length=15), nullable=False),
    sa.Column('call_to', sa.String(length=15), nullable=False),
    sa.Column('call_direction', sa.Enum('INCOMING', 'OUTGOING', name='calldirection'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=15), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('call_recording_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', 'GUEST', name='userrole'), nullable=True),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('last_week_performance_analysis', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('lead_qualification', sa.JSON(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('key_stakeholders', sa.JSON(), nullable=True),
    sa.Column('buyer_number', sa.String(length=15), nullable=False),
    sa.Column('seller_number', sa.String(length=15), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('INITIALIZED', 'PROCESSING', 'COMPLETE', name='processingstatus'), nullable=True),
    sa.Column('source', sa.Enum('PHONE', 'VIDEO_CALL', 'GOOGLE_MEETS', name='meetingsource'), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('diarization', sa.Text(), nullable=True),
    sa.Column('key_topics', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='actionstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call_context', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('INIT', 'IN_PROGRESS', 'COMPLETED', 'FAILURE', name='jobstatus'), nullable=True),
    sa.Column('s3_audio_url', sa.String(length=150), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id'),
    sa.UniqueConstraint('s3_audio_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('actions')
    op.drop_table('meetings')
    op.drop_table('deals')
    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('exotel_calls')
    op.drop_table('app_calls')
    op.drop_table('agencies')
    # ### end Alembic commands ###
