"""make username nullable

Revision ID: 230161774e72
Revises: 57684e827178
Create Date: 2025-05-14 01:15:34.835290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230161774e72'
down_revision = '57684e827178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
