"""add company name string to buyer model

Revision ID: 2319ae8a3abd
Revises: a339bc6255fe
Create Date: 2025-07-11 22:53:19.063598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2319ae8a3abd'
down_revision = 'a339bc6255fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
