"""make call_type nullable

Revision ID: 2d8eac8cbda0
Revises: 3ab9a223018f
Create Date: 2025-05-19 17:07:58.811675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d8eac8cbda0'
down_revision = '3ab9a223018f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_calls', schema=None) as batch_op:
        batch_op.alter_column('call_type',
               existing_type=postgresql.ENUM('INCOMING', 'OUTGOING', 'MISSED', name='calldirection'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_calls', schema=None) as batch_op:
        batch_op.alter_column('call_type',
               existing_type=postgresql.ENUM('INCOMING', 'OUTGOING', 'MISSED',  name='calldirection'),
               nullable=False)

    # ### end Alembic commands ###
