"""add deal status column and rename deal history column

Revision ID: 3ab9a223018f
Revises: 5e985743a5fa
Create Date: 2025-05-17 22:25:49.787930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab9a223018f'
down_revision = '5e985743a5fa'
branch_labels = None
depends_on = None

deal_status_enum = postgresql.ENUM(
    'open',
    'success',
    'failure',
    name='dealstatus',
    create_type=False
)


def upgrade():
    deal_status_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('type', deal_status_enum, nullable=True))
        batch_op.drop_column('deal_history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('history')
    deal_status_enum.drop(op.get_bind())

    # ### end Alembic commands ###
