"""add llm_analysis columns to meeting records

Revision ID: 4852c9819528
Revises: d614bc40b1b2
Create Date: 2025-06-01 22:00:14.027112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4852c9819528'
down_revision = 'd614bc40b1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_analytical_response', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('llm_descriptive_response', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('llm_descriptive_response')
        batch_op.drop_column('llm_analytical_response')

    # ### end Alembic commands ###
