"""fix buyer phone constraint to be unique per agency

Revision ID: 55c59b2af243
Revises: 8858763fe409
Create Date: 2025-07-23 22:55:41.539205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c59b2af243'
down_revision = '8858763fe409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_constraint('buyers_phone_key', type_='unique')
        batch_op.create_unique_constraint('uq_buyer_phone_agency', ['phone', 'agency_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_buyer_phone_agency', type_='unique')
        batch_op.create_unique_constraint('buyers_phone_key', ['phone'])

    # ### end Alembic commands ###
