"""change deal overview data type

Revision ID: 57684e827178
Revises: 64fee614bfc2
Create Date: 2025-05-12 23:54:59.779563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57684e827178'
down_revision = '64fee614bfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='overview::json',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
