"""add manager relationship to User; deal_history column to deal

Revision ID: 5e985743a5fa
Revises: bd12004582ce
Create Date: 2025-05-17 19:55:12.407925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e985743a5fa'
down_revision = 'bd12004582ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_history', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('deal_history')

    # ### end Alembic commands ###
