"""remove extra exotel app columns

Revision ID: 79dd9f55f47d
Revises: fa05238d7b8c
Create Date: 2025-04-20 22:14:37.828861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79dd9f55f47d'
down_revision = 'fa05238d7b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exotel_calls', schema=None) as batch_op:
        batch_op.drop_column('call_direction')
        batch_op.drop_column('call_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exotel_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_to', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('call_direction', postgresql.ENUM('INCOMING', 'OUTGOING', name='calldirection'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
