"""add key_highlights column to buyer

Revision ID: 80573c70a4ad
Revises: 55c59b2af243
Create Date: 2025-07-29 00:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80573c70a4ad'
down_revision = '55c59b2af243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_highlights', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_column('key_highlights')

    # ### end Alembic commands ### 