"""add_unique_constraint_to_agency_name

Revision ID: 8299a18527f8
Revises: e1c1bf16f830
Create Date: 2025-07-06 18:33:24.818295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8299a18527f8'
down_revision = 'e1c1bf16f830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, check if there are any duplicate agency names and handle them
    # This will fail the migration if duplicates exist, forcing manual cleanup
    connection = op.get_bind()
    
    # Check for duplicate names
    result = connection.execute(sa.text("""
        SELECT name, COUNT(*) as count 
        FROM agencies 
        GROUP BY name 
        HAVING COUNT(*) > 1
    """))
    
    duplicates = result.fetchall()
    if duplicates:
        duplicate_names = [row[0] for row in duplicates]
        raise Exception(f"Cannot add unique constraint: duplicate agency names found: {duplicate_names}. "
                       f"Please manually resolve duplicates before running this migration.")
    
    # Add unique constraint to agency name
    op.create_unique_constraint('uq_agencies_name', 'agencies', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_agencies_name', 'agencies', type_='unique')
    # ### end Alembic commands ###
