"""remove user_performances table

Revision ID: 8858763fe409
Revises: ff31b2c9c3c
Create Date: 2025-07-22 22:51:01.292529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8858763fe409'
down_revision = 'ff31b2c9c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_performances')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_performances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('intro', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rapport_building', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('need_realization', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('script_adherance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('objection_handling', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pricing_and_negotiation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('closure_and_next_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('conversation_structure_and_flow', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('avg_intro_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_rapport_building_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_need_realization_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_script_adherance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_objection_handling_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_pricing_and_negotiation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_closure_and_next_steps_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_conversation_structure_and_flow_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_avg_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_calls_analyzed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('performance_trend', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name='user_performances_seller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_performances_pkey'),
    sa.UniqueConstraint('seller_id', name='user_performances_seller_id_key')
    )
    # ### end Alembic commands ###
