"""Add detected_call_type and detected_product columns to meetings table

Revision ID: 94557cf0c781
Revises: cc54d38316c3
Create Date: 2025-08-03 19:23:47.247166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94557cf0c781'
down_revision = 'cc54d38316c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_call_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('detected_product', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('detected_product')
        batch_op.drop_column('detected_call_type')

    # ### end Alembic commands ###
