"""Add vonage_calls table for Vonage integration

Revision ID: vonage_integration_001
Revises: e7a5c2d9ab10
Create Date: 2025-01-15 20:03:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import UUID
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'vonage_integration_001'
down_revision = 'e7a5c2d9ab10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vonage_calls',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('conversation_uuid', sa.String(length=100), nullable=False),
    sa.Column('call_uuid', sa.String(length=100), nullable=True),
    sa.Column('recording_uuid', sa.String(length=100), nullable=True),
    sa.Column('call_from', sa.String(length=15), nullable=False),
    sa.Column('call_to', sa.String(length=15), nullable=False),
    sa.Column('call_status', sa.String(length=50), nullable=True),
    sa.Column('call_direction', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True, default=0),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('recording_status', sa.String(length=50), nullable=True),
    sa.Column('recording_format', sa.String(length=10), nullable=True),
    sa.Column('recording_size', sa.Integer(), nullable=True),
    sa.Column('has_call_event', sa.Boolean(), nullable=False, default=False),
    sa.Column('has_recording_event', sa.Boolean(), nullable=False, default=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False, default=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vonage_calls_conversation_uuid'), 'vonage_calls', ['conversation_uuid'], unique=False)
    op.create_index(op.f('ix_vonage_calls_call_from'), 'vonage_calls', ['call_from'], unique=False)
    op.create_index(op.f('ix_vonage_calls_start_time'), 'vonage_calls', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vonage_calls_start_time'), table_name='vonage_calls')
    op.drop_index(op.f('ix_vonage_calls_call_from'), table_name='vonage_calls')
    op.drop_index(op.f('ix_vonage_calls_conversation_uuid'), table_name='vonage_calls')
    op.drop_table('vonage_calls')
    # ### end Alembic commands ###
