"""Add product_details_analysis, objection_handling_analysis, and overall_performance_summary to call_performances table

Revision ID: bc7bb5cbaf96
Revises: 94557cf0c781
Create Date: 2025-08-03 20:09:51.734984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7bb5cbaf96'
down_revision = '94557cf0c781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_details_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('objection_handling_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('overall_performance_summary', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_performances', schema=None) as batch_op:
        batch_op.drop_column('overall_performance_summary')
        batch_op.drop_column('objection_handling_analysis')
        batch_op.drop_column('product_details_analysis')

    # ### end Alembic commands ###
