"""Change overall_summary from TEXT to JSON in meetings table

Revision ID: cc54d38316c3
Revises: 5a631b3a2295
Create Date: 2025-08-02 15:28:57.532242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc54d38316c3'
down_revision = '5a631b3a2295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom migration: Change TEXT to JSON with proper casting for PostgreSQL
    op.execute("ALTER TABLE meetings ALTER COLUMN overall_summary TYPE JSON USING CASE WHEN overall_summary IS NULL THEN NULL ELSE overall_summary::json END")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom migration: Change JSON back to TEXT with proper casting for PostgreSQL
    op.execute("ALTER TABLE meetings ALTER COLUMN overall_summary TYPE TEXT USING CASE WHEN overall_summary IS NULL THEN NULL ELSE overall_summary::text END")

    # ### end Alembic commands ###
