"""add new deal, meeting and action columns

Revision ID: d08163ba4dfb
Revises: bcc9894de768
Create Date: 2025-05-03 13:11:06.794959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd08163ba4dfb'
down_revision = 'bcc9894de768'
branch_labels = None
depends_on = None

action_type_enum = postgresql.ENUM(
    'suggested_action',
    'contextual_action',
    name='actiontype',
    create_type=False
)


def upgrade():
    action_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', action_type_enum, nullable=True))
        batch_op.add_column(sa.Column('reasoning', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signals', sa.JSON(), nullable=True))
        batch_op.drop_column('call_context')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=True))

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_signals', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('stage_reasoning', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('focus_areas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('risks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pain_points', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('solutions', sa.JSON(), nullable=True))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_notes', sa.Text(), nullable=True))
        batch_op.drop_column('key_topics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_topics', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('call_notes')

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('solutions')
        batch_op.drop_column('pain_points')
        batch_op.drop_column('risks')
        batch_op.drop_column('focus_areas')
        batch_op.drop_column('stage_reasoning')
        batch_op.drop_column('stage_signals')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_context', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('signals')
        batch_op.drop_column('reasoning')
        batch_op.drop_column('type')

    action_type_enum.drop(op.get_bind())

    # ### end Alembic commands ###
