"""change call_type in mobileAppCall to str

Revision ID: ed878b9cd251
Revises: 2d8eac8cbda0
Create Date: 2025-05-19 23:26:21.537113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed878b9cd251'
down_revision = '2d8eac8cbda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_calls', schema=None) as batch_op:
        batch_op.alter_column('call_type',
               existing_type=postgresql.ENUM('INCOMING', 'OUTGOING', name='calldirection'),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_calls', schema=None) as batch_op:
        batch_op.alter_column('call_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('INCOMING', 'OUTGOING', name='calldirection'),
               existing_nullable=True)

    # ### end Alembic commands ###
