"""Add overall_summary field to meetings table

Revision ID: f2f92ff9f21d
Revises: 55c59b2af243
Create Date: 2025-08-02 15:18:10.355373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f92ff9f21d'
down_revision = '55c59b2af243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('overall_summary')

    # ### end Alembic commands ###
