"""add new columns to meeting and mobile_app_call

Revision ID: fa05238d7b8c
Revises: 00d4e5c405dc
Create Date: 2025-04-20 00:40:27.798841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa05238d7b8c'
down_revision = '00d4e5c405dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_app_call_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_app_call_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyer_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('seller_number', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('seller_number')
        batch_op.drop_column('buyer_number')
        batch_op.drop_column('mobile_app_call_id')

    with op.batch_alter_table('app_calls', schema=None) as batch_op:
        batch_op.drop_column('mobile_app_call_id')

    # ### end Alembic commands ###
