"""add call performance model

Revision ID: ff31b2c9c3c
Revises: 2319ae8a3abd
Create Date: 2025-01-22 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ff31b2c9c3c'
down_revision = '2319ae8a3abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create call_performances table
    op.create_table('call_performances',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('meeting_id', sa.UUID(), nullable=False),
        sa.Column('intro', sa.JSON(), nullable=True),
        sa.Column('rapport_building', sa.JSON(), nullable=True),
        sa.Column('need_realization', sa.JSON(), nullable=True),
        sa.Column('script_adherance', sa.JSON(), nullable=True),
        sa.Column('objection_handling', sa.JSON(), nullable=True),
        sa.Column('pricing_and_negotiation', sa.JSON(), nullable=True),
        sa.Column('closure_and_next_steps', sa.JSON(), nullable=True),
        sa.Column('conversation_structure_and_flow', sa.JSON(), nullable=True),
        sa.Column('overall_score', sa.Float(), nullable=True),
        sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('meeting_id')
    )
    

    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_performances')
    # ### end Alembic commands ### 